In [49]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [50]:
# Importing the dataset using pandas
dataset = pd.read_csv(r'C:\Users\asus\Desktop\RT4\deep learning\car.csv')
dataset.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [51]:
# Create matrix of features and matrix of target variable.
X = dataset.iloc[:, 0:6].values
y = dataset.iloc[:, 6:7].values

In [52]:
labelencoder_X_0 = LabelEncoder()
X[:, 0] = labelencoder_X_0.fit_transform(X[:, 0])

In [53]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_4 = LabelEncoder()
X[:, 4] = labelencoder_X_4.fit_transform(X[:, 4])
labelencoder_X_5 = LabelEncoder()
X[:, 5] = labelencoder_X_5.fit_transform(X[:, 5])

In [54]:
labelencoder_y = LabelEncoder()
y[:,0] = labelencoder_y.fit_transform(y[:,0])

In [55]:
y[:]

array([[2],
       [2],
       [2],
       ..., 
       [2],
       [1],
       [3]], dtype=object)

In [56]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
labelencoder_X_3 = LabelEncoder()
X[:, 3] = labelencoder_X_3.fit_transform(X[:, 3])

In [57]:
print(labelencoder_X_1.inverse_transform([0,1,2,2,1,0]))

['high' 'low' 'med' 'med' 'low' 'high']


In [58]:
onehotencoder = OneHotEncoder(categorical_features = 'all')
X = onehotencoder.fit_transform(X).toarray()


In [59]:
onehotencoder1 = OneHotEncoder(categorical_features = 'all')
y= onehotencoder1.fit_transform(y).toarray()

In [60]:
X[:, 1:]

array([[ 0.,  0.,  1., ...,  0.,  1.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  1.],
       [ 0.,  0.,  1., ...,  1.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0., ...,  0.,  1.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  1.],
       [ 1.,  0.,  0., ...,  1.,  0.,  0.]])

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [62]:
X_train[:,:]

array([[ 1.,  0.,  0., ...,  0.,  1.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  1., ...,  0.,  1.,  0.],
       ..., 
       [ 0.,  1.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  1.],
       [ 1.,  0.,  0., ...,  0.,  1.,  0.]])

In [63]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [64]:
#Initializing Neural Network
classifier = Sequential()
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim =12, init = 'uniform', activation = 'relu', input_dim = 21))
classifier.add(Dense(output_dim = 12, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'softmax'))

C:\Users\asus\Miniconda3\envs\DL\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, kernel_initializer="uniform", activation="relu", input_dim=21)`
  after removing the cwd from sys.path.
C:\Users\asus\Miniconda3\envs\DL\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=12, kernel_initializer="uniform", activation="relu")`
  """
C:\Users\asus\Miniconda3\envs\DL\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=4, kernel_initializer="uniform", activation="softmax")`
  import sys


In [65]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [66]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
1382/1382 [==============================] - 2s 1ms/step - loss: 1.1237 - acc: 0.6896
Epoch 2/100
1382/1382 [==============================] - 1s 393us/step - loss: 0.5392 - acc: 0.6975
Epoch 3/100
1382/1382 [==============================] - 1s 384us/step - loss: 0.4461 - acc: 0.7402
Epoch 4/100
1382/1382 [==============================] - 1s 397us/step - loss: 0.3986 - acc: 0.7764
Epoch 5/100
1382/1382 [==============================] - 1s 396us/step - loss: 0.3469 - acc: 0.8582
Epoch 6/100
1382/1382 [==============================] - 1s 395us/step - loss: 0.2907 - acc: 0.9059
Epoch 7/100
1382/1382 [==============================] - 1s 397us/step - loss: 0.2437 - acc: 0.9088
Epoch 8/100
1382/1382 [==============================] - 1s 385us/step - loss: 0.2121 - acc: 0.9096
Epoch 9/100
1382/1382 [==============================] - 1s 396us/step - loss: 0.1929 - acc: 0.9088
Epoch 10/100
1382/1382 [==============================] - 1s 386us/step - loss: 0.1764 - acc: 0.9110
E

1382/1382 [==============================] - 1s 419us/step - loss: 0.0270 - acc: 0.9978
Epoch 83/100
1382/1382 [==============================] - 1s 429us/step - loss: 0.0255 - acc: 0.9971
Epoch 84/100
1382/1382 [==============================] - 1s 441us/step - loss: 0.0245 - acc: 0.9971
Epoch 85/100
1382/1382 [==============================] - 1s 408us/step - loss: 0.0282 - acc: 0.9957
Epoch 86/100
1382/1382 [==============================] - 1s 406us/step - loss: 0.0250 - acc: 0.9964
Epoch 87/100
1382/1382 [==============================] - 1s 385us/step - loss: 0.0209 - acc: 0.9978
Epoch 88/100
1382/1382 [==============================] - 1s 373us/step - loss: 0.0200 - acc: 0.9978
Epoch 89/100
1382/1382 [==============================] - 1s 385us/step - loss: 0.0192 - acc: 0.9978
Epoch 90/100
1382/1382 [==============================] - 1s 396us/step - loss: 0.0184 - acc: 0.9978
Epoch 91/100
1382/1382 [==============================] - 1s 407us/step - loss: 0.0177 - acc: 0.9978
Epo

In [67]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
print(y_pred)

[[False False  True False]
 [ True False False False]
 [False False  True False]
 ..., 
 [False False False  True]
 [False False  True False]
 [False False  True False]]


In [68]:
cm = accuracy_score(y_test, y_pred)
print(cm)

0.985549132948


In [69]:
# Accuracy of our model
accuracy =cm*100
print("The accuracy of our model is %2.1f %%" % accuracy)

The accuracy of our model is 98.6 %
